name: Java CI

on: [push]

jobs:
    build:
      environment: ECR_ENV
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Restore Cache
          uses: actions/cache@v2
          with:
            path: ~/.gradle/caches
            key: ${{ runner.os }}-gradle-${{ hashFIles('**/*.gradle')}}
            restore-keys: |
              ${{ runner.os }}-gradle-
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
        - name: Setup Gradlew
          run: gradle wrapper
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
        - name: Create Docker Image
          env:
            DOCKER_REPOSITORY: ${{secrets.DOCKER_REPOSITORY}}
          run: ./gradlew jibDockerBuild -Djib.container.environment=SLACK_APP_TOKEN="${{secrets.SLACK_APP_TOKEN}}",SLACK_BOT_TOKEN="${{secrets.SLACK_BOT_TOKEN}}"

