name: Java CI

on: [push]

jobs:
    build:
      environment: ECR_ENV
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
        - name: Setup Gradlew
          run: gradle wrapper
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
        - name: Build with Gradle
          run: ./gradlew build
        - name: Describe Docker Repository Name
          run: export DOCKER_REPOSITORY=${{secrets.DOCKER_REPOSITORY}}
        - name: Create Docker Image
          run: ./gradlew jibDockerBuild -Djib.container.environment=SLACK_APP_TOKEN="${{secrets.SLACK_APP_TOKEN}}",SLACK_BOT_TOKEN="${{secrets.SLACK_BOT_TOKEN}}"

