name: Java CI

on: [push]

jobs:
    build:
      environment: ECR_ENV
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        - name: Login ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1
        - name: Restore Cache
          uses: actions/cache@v2
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFIles('**/*.gradle*', '**/gradle-wrapper.properties')}}
            restore-keys: |
              ${{ runner.os }}-gradle-
        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
        - name: Setup Gradlew
          run: gradle wrapper
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
        - name: Build And Push
          env:
            DOCKER_REPOSITORY: ${{ steps.login-ecr.outputs.registry }}
          run: |
            ./gradlew jibDockerBuild
            docker push $DOCKER_REPOSITORY/slack-socket-mode-sample:latest
